version: "3"

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local

services:
  apisix:
    image: apache/apisix:3.6.0-debian
    restart: unless-stopped
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "80:9080/tcp"
      - "443:9443/tcp"
      - "9091:9091/tcp"
      - "9092:9092/tcp"
      - "9180:9180/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.5.13
    restart: unless-stopped
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

  dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    restart: always
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9000:9000/tcp"
    networks:
      - apisix